### ISSUE TITLE
AttributeError: module 'tracemoe' has no attribute '__version__'

### ISSUE THREAD

**Issue by kyuzaa** [fauzanardh/TraceMoe#1]
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    version=tracemoe.__version__,
AttributeError: module 'tracemoe' has no attribute '__version__'

**Comment by anysz** [comment]
This is because:
1. The Library don't have `__init__.py` file 
2. Since there's no `__init__.py` file, `import tracemoe`  wll do nothing

Check out the https://github.com/fauzanardh/TraceMoe/blob/master/setup.py#L13

>   Get rid [the tracemoe.__version__](https://github.com/fauzanardh/TraceMoe/blob/master/setup.py#L13) hard code them with current version (1.0.0)

**Comment by fauzanardh** [comment]
Should be working now, I forgot to change the setup.py file
